// Code generated by go-swagger; DO NOT EDIT.

// Package restapi social-naka-app
//
//  HTTP server in Go with Swagger endpoints definition
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
