// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "social-naka-app",
    "version": "0.0.1"
  },
  "paths": {
    "/events": {
      "get": {
        "description": "It gets all the Events\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Get all the Events",
        "operationId": "getEvents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/events/{id}": {
      "get": {
        "description": "It gets the event information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Gets a event by ID.",
        "operationId": "getEventbyID",
        "parameters": [
          {
            "type": "string",
            "description": "Event ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "description": "It delets the event information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Deletes a event by ID.",
        "operationId": "deleteEventbyID",
        "parameters": [
          {
            "type": "string",
            "description": "Event ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Status"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "patch": {
        "description": "It updates the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Updates an event by ID.",
        "operationId": "updateEventbyID",
        "parameters": [
          {
            "type": "string",
            "description": "Event ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "Event Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/event"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/loginUser": {
      "post": {
        "description": "It logins the User\n",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "login"
        ],
        "summary": "Logins the User",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "Login Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/loginUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/responses/Status"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/postEvent": {
      "post": {
        "description": "It registers the Event\n",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Post the Event",
        "operationId": "postEvent",
        "parameters": [
          {
            "name": "Event Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/event"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/registerUser": {
      "post": {
        "description": "It registers the User\n",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Registers the User",
        "operationId": "registerUser",
        "parameters": [
          {
            "name": "User Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/registrationResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "409": {
            "$ref": "#/responses/UserExists"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "It gets all the Users\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Get all the Users",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/userResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "description": "It gets the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Gets a user by ID.",
        "operationId": "getUserbyID",
        "parameters": [
          {
            "type": "string",
            "description": "User ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/registrationResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "description": "It delets the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Deletes a user by ID.",
        "operationId": "deleteUserbyID",
        "parameters": [
          {
            "type": "string",
            "description": "User ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/Status"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "patch": {
        "description": "It updates the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Updates a user by ID.",
        "operationId": "updateUserbyID",
        "parameters": [
          {
            "type": "string",
            "description": "User ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "User Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/registrationResponse"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "409": {
            "$ref": "#/responses/UserExists"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    }
  },
  "definitions": {
    "event": {
      "type": "object",
      "properties": {
        "approver_id": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "event_date": {
          "type": "string",
          "format": "date",
          "x-nullable": true
        },
        "event_description": {
          "type": "string"
        },
        "event_location": {
          "type": "string"
        },
        "event_name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "is_active": {
          "type": "boolean"
        },
        "is_verified": {
          "type": "boolean"
        },
        "updated_at": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "eventResponse": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/definitions/event"
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/event"
          }
        },
        "response": {
          "$ref": "#/definitions/response"
        }
      }
    },
    "loginUser": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "registrationResponse": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "#/definitions/response"
        },
        "user": {
          "$ref": "#/definitions/user"
        }
      }
    },
    "response": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "dob": {
          "type": "string",
          "format": "date",
          "x-nullable": true
        },
        "email_address": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "house_name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "is_active": {
          "type": "boolean"
        },
        "is_staying_here": {
          "type": "boolean"
        },
        "last_name": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "mobile_no": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "role_name": {
          "type": "string"
        },
        "sex": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "userResponse": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "#/definitions/response"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/user"
          }
        }
      }
    }
  },
  "responses": {
    "BadRequest": {
      "description": "The api is Unauthorized",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "NotFound": {
      "description": "The api is not found",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "Status": {
      "description": "API Custom Status",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "UnauthorizedError": {
      "description": "The api is Unauthorized",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "UserExists": {
      "description": "The user already exists",
      "schema": {
        "$ref": "#/definitions/response"
      }
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-API-Key",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "social-naka-app",
    "version": "0.0.1"
  },
  "paths": {
    "/events": {
      "get": {
        "description": "It gets all the Events\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Get all the Events",
        "operationId": "getEvents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    },
    "/events/{id}": {
      "get": {
        "description": "It gets the event information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Gets a event by ID.",
        "operationId": "getEventbyID",
        "parameters": [
          {
            "type": "string",
            "description": "Event ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      },
      "delete": {
        "description": "It delets the event information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Deletes a event by ID.",
        "operationId": "deleteEventbyID",
        "parameters": [
          {
            "type": "string",
            "description": "Event ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "API Custom Status",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      },
      "patch": {
        "description": "It updates the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Updates an event by ID.",
        "operationId": "updateEventbyID",
        "parameters": [
          {
            "type": "string",
            "description": "Event ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "Event Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/event"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    },
    "/loginUser": {
      "post": {
        "description": "It logins the User\n",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "login"
        ],
        "summary": "Logins the User",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "Login Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/loginUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "description": "API Custom Status",
              "schema": {
                "$ref": "#/definitions/response"
              }
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    },
    "/postEvent": {
      "post": {
        "description": "It registers the Event\n",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "events"
        ],
        "summary": "Post the Event",
        "operationId": "postEvent",
        "parameters": [
          {
            "name": "Event Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/event"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/eventResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    },
    "/registerUser": {
      "post": {
        "description": "It registers the User\n",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Registers the User",
        "operationId": "registerUser",
        "parameters": [
          {
            "name": "User Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/registrationResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "409": {
            "description": "The user already exists",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "It gets all the Users\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Get all the Users",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/userResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "description": "It gets the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Gets a user by ID.",
        "operationId": "getUserbyID",
        "parameters": [
          {
            "type": "string",
            "description": "User ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/registrationResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      },
      "delete": {
        "description": "It delets the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Deletes a user by ID.",
        "operationId": "deleteUserbyID",
        "parameters": [
          {
            "type": "string",
            "description": "User ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "API Custom Status",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      },
      "patch": {
        "description": "It updates the user information details by ID\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "Updates a user by ID.",
        "operationId": "updateUserbyID",
        "parameters": [
          {
            "type": "string",
            "description": "User ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "User Body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/user"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/registrationResponse"
            }
          },
          "400": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "401": {
            "description": "The api is Unauthorized",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "The api is not found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "409": {
            "description": "The user already exists",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "event": {
      "type": "object",
      "properties": {
        "approver_id": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "event_date": {
          "type": "string",
          "format": "date",
          "x-nullable": true
        },
        "event_description": {
          "type": "string"
        },
        "event_location": {
          "type": "string"
        },
        "event_name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "is_active": {
          "type": "boolean"
        },
        "is_verified": {
          "type": "boolean"
        },
        "updated_at": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "eventResponse": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/definitions/event"
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/event"
          }
        },
        "response": {
          "$ref": "#/definitions/response"
        }
      }
    },
    "loginUser": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "registrationResponse": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "#/definitions/response"
        },
        "user": {
          "$ref": "#/definitions/user"
        }
      }
    },
    "response": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "dob": {
          "type": "string",
          "format": "date",
          "x-nullable": true
        },
        "email_address": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "house_name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "is_active": {
          "type": "boolean"
        },
        "is_staying_here": {
          "type": "boolean"
        },
        "last_name": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "mobile_no": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "role_name": {
          "type": "string"
        },
        "sex": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "userResponse": {
      "type": "object",
      "properties": {
        "response": {
          "$ref": "#/definitions/response"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/user"
          }
        }
      }
    }
  },
  "responses": {
    "BadRequest": {
      "description": "The api is Unauthorized",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "NotFound": {
      "description": "The api is not found",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "Status": {
      "description": "API Custom Status",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "UnauthorizedError": {
      "description": "The api is Unauthorized",
      "schema": {
        "$ref": "#/definitions/response"
      }
    },
    "UserExists": {
      "description": "The user already exists",
      "schema": {
        "$ref": "#/definitions/response"
      }
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-API-Key",
      "in": "header"
    }
  }
}`))
}
