// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/amanw/social-naka-app-services/pkg/api/restapi/operations/events"
	"github.com/amanw/social-naka-app-services/pkg/api/restapi/operations/login"
	"github.com/amanw/social-naka-app-services/pkg/api/restapi/operations/posts"
	"github.com/amanw/social-naka-app-services/pkg/api/restapi/operations/users"
)

// NewSocialNakaAppAPI creates a new SocialNakaApp instance
func NewSocialNakaAppAPI(spec *loads.Document) *SocialNakaAppAPI {
	return &SocialNakaAppAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		PostsCreatePostHandler: posts.CreatePostHandlerFunc(func(params posts.CreatePostParams) middleware.Responder {
			return middleware.NotImplemented("operation posts.CreatePost has not yet been implemented")
		}),
		EventsDeleteEventbyIDHandler: events.DeleteEventbyIDHandlerFunc(func(params events.DeleteEventbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation events.DeleteEventbyID has not yet been implemented")
		}),
		PostsDeletePostbyIDHandler: posts.DeletePostbyIDHandlerFunc(func(params posts.DeletePostbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation posts.DeletePostbyID has not yet been implemented")
		}),
		UsersDeleteUserbyIDHandler: users.DeleteUserbyIDHandlerFunc(func(params users.DeleteUserbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation users.DeleteUserbyID has not yet been implemented")
		}),
		EventsGetEventbyIDHandler: events.GetEventbyIDHandlerFunc(func(params events.GetEventbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation events.GetEventbyID has not yet been implemented")
		}),
		EventsGetEventsHandler: events.GetEventsHandlerFunc(func(params events.GetEventsParams) middleware.Responder {
			return middleware.NotImplemented("operation events.GetEvents has not yet been implemented")
		}),
		PostsGetPostbyIDHandler: posts.GetPostbyIDHandlerFunc(func(params posts.GetPostbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation posts.GetPostbyID has not yet been implemented")
		}),
		PostsGetPostsHandler: posts.GetPostsHandlerFunc(func(params posts.GetPostsParams) middleware.Responder {
			return middleware.NotImplemented("operation posts.GetPosts has not yet been implemented")
		}),
		UsersGetUserbyIDHandler: users.GetUserbyIDHandlerFunc(func(params users.GetUserbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation users.GetUserbyID has not yet been implemented")
		}),
		UsersGetUsersHandler: users.GetUsersHandlerFunc(func(params users.GetUsersParams) middleware.Responder {
			return middleware.NotImplemented("operation users.GetUsers has not yet been implemented")
		}),
		LoginLoginUserHandler: login.LoginUserHandlerFunc(func(params login.LoginUserParams) middleware.Responder {
			return middleware.NotImplemented("operation login.LoginUser has not yet been implemented")
		}),
		EventsPostEventHandler: events.PostEventHandlerFunc(func(params events.PostEventParams) middleware.Responder {
			return middleware.NotImplemented("operation events.PostEvent has not yet been implemented")
		}),
		UsersRegisterUserHandler: users.RegisterUserHandlerFunc(func(params users.RegisterUserParams) middleware.Responder {
			return middleware.NotImplemented("operation users.RegisterUser has not yet been implemented")
		}),
		EventsUpdateEventbyIDHandler: events.UpdateEventbyIDHandlerFunc(func(params events.UpdateEventbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation events.UpdateEventbyID has not yet been implemented")
		}),
		PostsUpdatePostbyIDHandler: posts.UpdatePostbyIDHandlerFunc(func(params posts.UpdatePostbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation posts.UpdatePostbyID has not yet been implemented")
		}),
		UsersUpdateUserbyIDHandler: users.UpdateUserbyIDHandlerFunc(func(params users.UpdateUserbyIDParams) middleware.Responder {
			return middleware.NotImplemented("operation users.UpdateUserbyID has not yet been implemented")
		}),
	}
}

/*SocialNakaAppAPI HTTP server in Go with Swagger endpoints definition */
type SocialNakaAppAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// PostsCreatePostHandler sets the operation handler for the create post operation
	PostsCreatePostHandler posts.CreatePostHandler
	// EventsDeleteEventbyIDHandler sets the operation handler for the delete eventby ID operation
	EventsDeleteEventbyIDHandler events.DeleteEventbyIDHandler
	// PostsDeletePostbyIDHandler sets the operation handler for the delete postby ID operation
	PostsDeletePostbyIDHandler posts.DeletePostbyIDHandler
	// UsersDeleteUserbyIDHandler sets the operation handler for the delete userby ID operation
	UsersDeleteUserbyIDHandler users.DeleteUserbyIDHandler
	// EventsGetEventbyIDHandler sets the operation handler for the get eventby ID operation
	EventsGetEventbyIDHandler events.GetEventbyIDHandler
	// EventsGetEventsHandler sets the operation handler for the get events operation
	EventsGetEventsHandler events.GetEventsHandler
	// PostsGetPostbyIDHandler sets the operation handler for the get postby ID operation
	PostsGetPostbyIDHandler posts.GetPostbyIDHandler
	// PostsGetPostsHandler sets the operation handler for the get posts operation
	PostsGetPostsHandler posts.GetPostsHandler
	// UsersGetUserbyIDHandler sets the operation handler for the get userby ID operation
	UsersGetUserbyIDHandler users.GetUserbyIDHandler
	// UsersGetUsersHandler sets the operation handler for the get users operation
	UsersGetUsersHandler users.GetUsersHandler
	// LoginLoginUserHandler sets the operation handler for the login user operation
	LoginLoginUserHandler login.LoginUserHandler
	// EventsPostEventHandler sets the operation handler for the post event operation
	EventsPostEventHandler events.PostEventHandler
	// UsersRegisterUserHandler sets the operation handler for the register user operation
	UsersRegisterUserHandler users.RegisterUserHandler
	// EventsUpdateEventbyIDHandler sets the operation handler for the update eventby ID operation
	EventsUpdateEventbyIDHandler events.UpdateEventbyIDHandler
	// PostsUpdatePostbyIDHandler sets the operation handler for the update postby ID operation
	PostsUpdatePostbyIDHandler posts.UpdatePostbyIDHandler
	// UsersUpdateUserbyIDHandler sets the operation handler for the update userby ID operation
	UsersUpdateUserbyIDHandler users.UpdateUserbyIDHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *SocialNakaAppAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SocialNakaAppAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SocialNakaAppAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SocialNakaAppAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SocialNakaAppAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SocialNakaAppAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SocialNakaAppAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SocialNakaAppAPI
func (o *SocialNakaAppAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.PostsCreatePostHandler == nil {
		unregistered = append(unregistered, "posts.CreatePostHandler")
	}
	if o.EventsDeleteEventbyIDHandler == nil {
		unregistered = append(unregistered, "events.DeleteEventbyIDHandler")
	}
	if o.PostsDeletePostbyIDHandler == nil {
		unregistered = append(unregistered, "posts.DeletePostbyIDHandler")
	}
	if o.UsersDeleteUserbyIDHandler == nil {
		unregistered = append(unregistered, "users.DeleteUserbyIDHandler")
	}
	if o.EventsGetEventbyIDHandler == nil {
		unregistered = append(unregistered, "events.GetEventbyIDHandler")
	}
	if o.EventsGetEventsHandler == nil {
		unregistered = append(unregistered, "events.GetEventsHandler")
	}
	if o.PostsGetPostbyIDHandler == nil {
		unregistered = append(unregistered, "posts.GetPostbyIDHandler")
	}
	if o.PostsGetPostsHandler == nil {
		unregistered = append(unregistered, "posts.GetPostsHandler")
	}
	if o.UsersGetUserbyIDHandler == nil {
		unregistered = append(unregistered, "users.GetUserbyIDHandler")
	}
	if o.UsersGetUsersHandler == nil {
		unregistered = append(unregistered, "users.GetUsersHandler")
	}
	if o.LoginLoginUserHandler == nil {
		unregistered = append(unregistered, "login.LoginUserHandler")
	}
	if o.EventsPostEventHandler == nil {
		unregistered = append(unregistered, "events.PostEventHandler")
	}
	if o.UsersRegisterUserHandler == nil {
		unregistered = append(unregistered, "users.RegisterUserHandler")
	}
	if o.EventsUpdateEventbyIDHandler == nil {
		unregistered = append(unregistered, "events.UpdateEventbyIDHandler")
	}
	if o.PostsUpdatePostbyIDHandler == nil {
		unregistered = append(unregistered, "posts.UpdatePostbyIDHandler")
	}
	if o.UsersUpdateUserbyIDHandler == nil {
		unregistered = append(unregistered, "users.UpdateUserbyIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SocialNakaAppAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SocialNakaAppAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *SocialNakaAppAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *SocialNakaAppAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *SocialNakaAppAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SocialNakaAppAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the social naka app API
func (o *SocialNakaAppAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SocialNakaAppAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/createPost"] = posts.NewCreatePost(o.context, o.PostsCreatePostHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/events/{id}"] = events.NewDeleteEventbyID(o.context, o.EventsDeleteEventbyIDHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/posts/{id}"] = posts.NewDeletePostbyID(o.context, o.PostsDeletePostbyIDHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{id}"] = users.NewDeleteUserbyID(o.context, o.UsersDeleteUserbyIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/events/{id}"] = events.NewGetEventbyID(o.context, o.EventsGetEventbyIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/events"] = events.NewGetEvents(o.context, o.EventsGetEventsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts/{id}"] = posts.NewGetPostbyID(o.context, o.PostsGetPostbyIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts"] = posts.NewGetPosts(o.context, o.PostsGetPostsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{id}"] = users.NewGetUserbyID(o.context, o.UsersGetUserbyIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = users.NewGetUsers(o.context, o.UsersGetUsersHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/loginUser"] = login.NewLoginUser(o.context, o.LoginLoginUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/postEvent"] = events.NewPostEvent(o.context, o.EventsPostEventHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/registerUser"] = users.NewRegisterUser(o.context, o.UsersRegisterUserHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/events/{id}"] = events.NewUpdateEventbyID(o.context, o.EventsUpdateEventbyIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/posts/{id}"] = posts.NewUpdatePostbyID(o.context, o.PostsUpdatePostbyIDHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/users/{id}"] = users.NewUpdateUserbyID(o.context, o.UsersUpdateUserbyIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SocialNakaAppAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SocialNakaAppAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SocialNakaAppAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SocialNakaAppAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *SocialNakaAppAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
