// Code generated by go-swagger; DO NOT EDIT.

package events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventbyIDHandlerFunc turns a function with the right signature into a get eventby ID handler
type GetEventbyIDHandlerFunc func(GetEventbyIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventbyIDHandlerFunc) Handle(params GetEventbyIDParams) middleware.Responder {
	return fn(params)
}

// GetEventbyIDHandler interface for that can handle valid get eventby ID params
type GetEventbyIDHandler interface {
	Handle(GetEventbyIDParams) middleware.Responder
}

// NewGetEventbyID creates a new http.Handler for the get eventby ID operation
func NewGetEventbyID(ctx *middleware.Context, handler GetEventbyIDHandler) *GetEventbyID {
	return &GetEventbyID{Context: ctx, Handler: handler}
}

/*GetEventbyID swagger:route GET /events/{id} events getEventbyId

Gets a event by ID.

It gets the event information details by ID


*/
type GetEventbyID struct {
	Context *middleware.Context
	Handler GetEventbyIDHandler
}

func (o *GetEventbyID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEventbyIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
