// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/amanw/social-naka-app-services/pkg/api/models"
)

// CreatePostOKCode is the HTTP code returned for type CreatePostOK
const CreatePostOKCode int = 200

/*CreatePostOK OK

swagger:response createPostOK
*/
type CreatePostOK struct {

	/*
	  In: Body
	*/
	Payload *models.PostResponse `json:"body,omitempty"`
}

// NewCreatePostOK creates CreatePostOK with default headers values
func NewCreatePostOK() *CreatePostOK {

	return &CreatePostOK{}
}

// WithPayload adds the payload to the create post o k response
func (o *CreatePostOK) WithPayload(payload *models.PostResponse) *CreatePostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post o k response
func (o *CreatePostOK) SetPayload(payload *models.PostResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePostBadRequestCode is the HTTP code returned for type CreatePostBadRequest
const CreatePostBadRequestCode int = 400

/*CreatePostBadRequest The api is Unauthorized

swagger:response createPostBadRequest
*/
type CreatePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreatePostBadRequest creates CreatePostBadRequest with default headers values
func NewCreatePostBadRequest() *CreatePostBadRequest {

	return &CreatePostBadRequest{}
}

// WithPayload adds the payload to the create post bad request response
func (o *CreatePostBadRequest) WithPayload(payload *models.Response) *CreatePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post bad request response
func (o *CreatePostBadRequest) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePostUnauthorizedCode is the HTTP code returned for type CreatePostUnauthorized
const CreatePostUnauthorizedCode int = 401

/*CreatePostUnauthorized The api is Unauthorized

swagger:response createPostUnauthorized
*/
type CreatePostUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreatePostUnauthorized creates CreatePostUnauthorized with default headers values
func NewCreatePostUnauthorized() *CreatePostUnauthorized {

	return &CreatePostUnauthorized{}
}

// WithPayload adds the payload to the create post unauthorized response
func (o *CreatePostUnauthorized) WithPayload(payload *models.Response) *CreatePostUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post unauthorized response
func (o *CreatePostUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePostNotFoundCode is the HTTP code returned for type CreatePostNotFound
const CreatePostNotFoundCode int = 404

/*CreatePostNotFound The api is not found

swagger:response createPostNotFound
*/
type CreatePostNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreatePostNotFound creates CreatePostNotFound with default headers values
func NewCreatePostNotFound() *CreatePostNotFound {

	return &CreatePostNotFound{}
}

// WithPayload adds the payload to the create post not found response
func (o *CreatePostNotFound) WithPayload(payload *models.Response) *CreatePostNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post not found response
func (o *CreatePostNotFound) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePostInternalServerErrorCode is the HTTP code returned for type CreatePostInternalServerError
const CreatePostInternalServerErrorCode int = 500

/*CreatePostInternalServerError Internal Server Error

swagger:response createPostInternalServerError
*/
type CreatePostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewCreatePostInternalServerError creates CreatePostInternalServerError with default headers values
func NewCreatePostInternalServerError() *CreatePostInternalServerError {

	return &CreatePostInternalServerError{}
}

// WithPayload adds the payload to the create post internal server error response
func (o *CreatePostInternalServerError) WithPayload(payload *models.Response) *CreatePostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create post internal server error response
func (o *CreatePostInternalServerError) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
