// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/amanw/social-naka-app-services/pkg/api/models"
)

// DeletePostbyIDOKCode is the HTTP code returned for type DeletePostbyIDOK
const DeletePostbyIDOKCode int = 200

/*DeletePostbyIDOK API Custom Status

swagger:response deletePostbyIdOK
*/
type DeletePostbyIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeletePostbyIDOK creates DeletePostbyIDOK with default headers values
func NewDeletePostbyIDOK() *DeletePostbyIDOK {

	return &DeletePostbyIDOK{}
}

// WithPayload adds the payload to the delete postby Id o k response
func (o *DeletePostbyIDOK) WithPayload(payload *models.Response) *DeletePostbyIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete postby Id o k response
func (o *DeletePostbyIDOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostbyIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostbyIDBadRequestCode is the HTTP code returned for type DeletePostbyIDBadRequest
const DeletePostbyIDBadRequestCode int = 400

/*DeletePostbyIDBadRequest The api is Unauthorized

swagger:response deletePostbyIdBadRequest
*/
type DeletePostbyIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeletePostbyIDBadRequest creates DeletePostbyIDBadRequest with default headers values
func NewDeletePostbyIDBadRequest() *DeletePostbyIDBadRequest {

	return &DeletePostbyIDBadRequest{}
}

// WithPayload adds the payload to the delete postby Id bad request response
func (o *DeletePostbyIDBadRequest) WithPayload(payload *models.Response) *DeletePostbyIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete postby Id bad request response
func (o *DeletePostbyIDBadRequest) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostbyIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostbyIDUnauthorizedCode is the HTTP code returned for type DeletePostbyIDUnauthorized
const DeletePostbyIDUnauthorizedCode int = 401

/*DeletePostbyIDUnauthorized The api is Unauthorized

swagger:response deletePostbyIdUnauthorized
*/
type DeletePostbyIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeletePostbyIDUnauthorized creates DeletePostbyIDUnauthorized with default headers values
func NewDeletePostbyIDUnauthorized() *DeletePostbyIDUnauthorized {

	return &DeletePostbyIDUnauthorized{}
}

// WithPayload adds the payload to the delete postby Id unauthorized response
func (o *DeletePostbyIDUnauthorized) WithPayload(payload *models.Response) *DeletePostbyIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete postby Id unauthorized response
func (o *DeletePostbyIDUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostbyIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostbyIDNotFoundCode is the HTTP code returned for type DeletePostbyIDNotFound
const DeletePostbyIDNotFoundCode int = 404

/*DeletePostbyIDNotFound The api is not found

swagger:response deletePostbyIdNotFound
*/
type DeletePostbyIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeletePostbyIDNotFound creates DeletePostbyIDNotFound with default headers values
func NewDeletePostbyIDNotFound() *DeletePostbyIDNotFound {

	return &DeletePostbyIDNotFound{}
}

// WithPayload adds the payload to the delete postby Id not found response
func (o *DeletePostbyIDNotFound) WithPayload(payload *models.Response) *DeletePostbyIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete postby Id not found response
func (o *DeletePostbyIDNotFound) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostbyIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletePostbyIDInternalServerErrorCode is the HTTP code returned for type DeletePostbyIDInternalServerError
const DeletePostbyIDInternalServerErrorCode int = 500

/*DeletePostbyIDInternalServerError Internal Server Error

swagger:response deletePostbyIdInternalServerError
*/
type DeletePostbyIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeletePostbyIDInternalServerError creates DeletePostbyIDInternalServerError with default headers values
func NewDeletePostbyIDInternalServerError() *DeletePostbyIDInternalServerError {

	return &DeletePostbyIDInternalServerError{}
}

// WithPayload adds the payload to the delete postby Id internal server error response
func (o *DeletePostbyIDInternalServerError) WithPayload(payload *models.Response) *DeletePostbyIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete postby Id internal server error response
func (o *DeletePostbyIDInternalServerError) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePostbyIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
