// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/amanw/social-naka-app-services/pkg/api/models"
)

// GetPostsOKCode is the HTTP code returned for type GetPostsOK
const GetPostsOKCode int = 200

/*GetPostsOK OK

swagger:response getPostsOK
*/
type GetPostsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PostResponse `json:"body,omitempty"`
}

// NewGetPostsOK creates GetPostsOK with default headers values
func NewGetPostsOK() *GetPostsOK {

	return &GetPostsOK{}
}

// WithPayload adds the payload to the get posts o k response
func (o *GetPostsOK) WithPayload(payload *models.PostResponse) *GetPostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts o k response
func (o *GetPostsOK) SetPayload(payload *models.PostResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostsBadRequestCode is the HTTP code returned for type GetPostsBadRequest
const GetPostsBadRequestCode int = 400

/*GetPostsBadRequest The api is Unauthorized

swagger:response getPostsBadRequest
*/
type GetPostsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetPostsBadRequest creates GetPostsBadRequest with default headers values
func NewGetPostsBadRequest() *GetPostsBadRequest {

	return &GetPostsBadRequest{}
}

// WithPayload adds the payload to the get posts bad request response
func (o *GetPostsBadRequest) WithPayload(payload *models.Response) *GetPostsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts bad request response
func (o *GetPostsBadRequest) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostsUnauthorizedCode is the HTTP code returned for type GetPostsUnauthorized
const GetPostsUnauthorizedCode int = 401

/*GetPostsUnauthorized The api is Unauthorized

swagger:response getPostsUnauthorized
*/
type GetPostsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetPostsUnauthorized creates GetPostsUnauthorized with default headers values
func NewGetPostsUnauthorized() *GetPostsUnauthorized {

	return &GetPostsUnauthorized{}
}

// WithPayload adds the payload to the get posts unauthorized response
func (o *GetPostsUnauthorized) WithPayload(payload *models.Response) *GetPostsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts unauthorized response
func (o *GetPostsUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostsNotFoundCode is the HTTP code returned for type GetPostsNotFound
const GetPostsNotFoundCode int = 404

/*GetPostsNotFound The api is not found

swagger:response getPostsNotFound
*/
type GetPostsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetPostsNotFound creates GetPostsNotFound with default headers values
func NewGetPostsNotFound() *GetPostsNotFound {

	return &GetPostsNotFound{}
}

// WithPayload adds the payload to the get posts not found response
func (o *GetPostsNotFound) WithPayload(payload *models.Response) *GetPostsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts not found response
func (o *GetPostsNotFound) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostsInternalServerErrorCode is the HTTP code returned for type GetPostsInternalServerError
const GetPostsInternalServerErrorCode int = 500

/*GetPostsInternalServerError Internal Server Error

swagger:response getPostsInternalServerError
*/
type GetPostsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetPostsInternalServerError creates GetPostsInternalServerError with default headers values
func NewGetPostsInternalServerError() *GetPostsInternalServerError {

	return &GetPostsInternalServerError{}
}

// WithPayload adds the payload to the get posts internal server error response
func (o *GetPostsInternalServerError) WithPayload(payload *models.Response) *GetPostsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts internal server error response
func (o *GetPostsInternalServerError) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
