// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/amanw/social-naka-app-services/pkg/api/models"
)

// DeleteUserbyIDOKCode is the HTTP code returned for type DeleteUserbyIDOK
const DeleteUserbyIDOKCode int = 200

/*DeleteUserbyIDOK API Custom Status

swagger:response deleteUserbyIdOK
*/
type DeleteUserbyIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserbyIDOK creates DeleteUserbyIDOK with default headers values
func NewDeleteUserbyIDOK() *DeleteUserbyIDOK {

	return &DeleteUserbyIDOK{}
}

// WithPayload adds the payload to the delete userby Id o k response
func (o *DeleteUserbyIDOK) WithPayload(payload *models.Error) *DeleteUserbyIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete userby Id o k response
func (o *DeleteUserbyIDOK) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserbyIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserbyIDBadRequestCode is the HTTP code returned for type DeleteUserbyIDBadRequest
const DeleteUserbyIDBadRequestCode int = 400

/*DeleteUserbyIDBadRequest The api is Unauthorized

swagger:response deleteUserbyIdBadRequest
*/
type DeleteUserbyIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserbyIDBadRequest creates DeleteUserbyIDBadRequest with default headers values
func NewDeleteUserbyIDBadRequest() *DeleteUserbyIDBadRequest {

	return &DeleteUserbyIDBadRequest{}
}

// WithPayload adds the payload to the delete userby Id bad request response
func (o *DeleteUserbyIDBadRequest) WithPayload(payload *models.Error) *DeleteUserbyIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete userby Id bad request response
func (o *DeleteUserbyIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserbyIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserbyIDUnauthorizedCode is the HTTP code returned for type DeleteUserbyIDUnauthorized
const DeleteUserbyIDUnauthorizedCode int = 401

/*DeleteUserbyIDUnauthorized The api is Unauthorized

swagger:response deleteUserbyIdUnauthorized
*/
type DeleteUserbyIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserbyIDUnauthorized creates DeleteUserbyIDUnauthorized with default headers values
func NewDeleteUserbyIDUnauthorized() *DeleteUserbyIDUnauthorized {

	return &DeleteUserbyIDUnauthorized{}
}

// WithPayload adds the payload to the delete userby Id unauthorized response
func (o *DeleteUserbyIDUnauthorized) WithPayload(payload *models.Error) *DeleteUserbyIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete userby Id unauthorized response
func (o *DeleteUserbyIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserbyIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserbyIDNotFoundCode is the HTTP code returned for type DeleteUserbyIDNotFound
const DeleteUserbyIDNotFoundCode int = 404

/*DeleteUserbyIDNotFound The api is not found

swagger:response deleteUserbyIdNotFound
*/
type DeleteUserbyIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserbyIDNotFound creates DeleteUserbyIDNotFound with default headers values
func NewDeleteUserbyIDNotFound() *DeleteUserbyIDNotFound {

	return &DeleteUserbyIDNotFound{}
}

// WithPayload adds the payload to the delete userby Id not found response
func (o *DeleteUserbyIDNotFound) WithPayload(payload *models.Error) *DeleteUserbyIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete userby Id not found response
func (o *DeleteUserbyIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserbyIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserbyIDInternalServerErrorCode is the HTTP code returned for type DeleteUserbyIDInternalServerError
const DeleteUserbyIDInternalServerErrorCode int = 500

/*DeleteUserbyIDInternalServerError Internal Server Error

swagger:response deleteUserbyIdInternalServerError
*/
type DeleteUserbyIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserbyIDInternalServerError creates DeleteUserbyIDInternalServerError with default headers values
func NewDeleteUserbyIDInternalServerError() *DeleteUserbyIDInternalServerError {

	return &DeleteUserbyIDInternalServerError{}
}

// WithPayload adds the payload to the delete userby Id internal server error response
func (o *DeleteUserbyIDInternalServerError) WithPayload(payload *models.Error) *DeleteUserbyIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete userby Id internal server error response
func (o *DeleteUserbyIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserbyIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
